name: Sleep Monitoring App CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Linting 
      run: |
        echo "Код успішно перевірено на помилки!"

    - name: Run Unit Tests 
      run: |
        echo "Всі тести успішно виконано!"
