name: Sleep Monitoring App CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Linting Tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Linting (Перевірка коду на помилки)
      run: |
        # Перевірка синтаксису. Якщо код порожній — цей крок просто успішно завершиться.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
